In [1]:
import pandas as pd
import numpy as np
import time

# import matplotlib.pyplot as plt
# import seaborn as sns

In [2]:
from sklearn.model_selection import train_test_split, KFold
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor, ExtraTreesRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LassoLars, Ridge, BayesianRidge, Lasso, LinearRegression, HuberRegressor, PassiveAggressiveRegressor, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.dummy import DummyRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score # mean_squared_log_error

In [3]:
df = pd.read_csv("./../data/transform_diamonds.csv")
df

,Shape_CUSHION,Shape_EMERALD,Shape_HEART,Shape_MARQUISE,Shape_OVAL,Shape_PEAR,Shape_PRINCESS,Shape_ROUND,Weight,Clarity,Colour,Cut,Polish,Symmetry,Fluorescence,Price,Length,Width,Depth
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.549805,3.0,17.0,3.0,3.0,2.0,0.0,1378.65,5.050781,4.351562,2.939453
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.500000,8.0,19.0,3.0,3.0,2.0,2.0,1379.74,4.601562,4.308594,2.919922
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.509766,5.0,14.0,3.0,3.0,2.0,0.0,1380.19,4.710938,4.351562,2.939453
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.500000,5.0,14.0,3.0,3.0,2.0,0.0,1380.61,4.910156,4.261719,2.880859
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.529785,4.0,18.0,3.0,2.0,2.0,0.0,1383.13,4.699219,4.460938,3.009766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,4.0,17.0,3.0,3.0,3.0,0.0,2453.10,5.000000,5.039062,3.179688
5891,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,4.0,17.0,3.0,3.0,3.0,0.0,2453.10,5.031250,5.058594,3.160156
5892,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,5.0,18.0,2.0,3.0,2.0,0.0,2453.20,4.929688,4.960938,3.189453
5893,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.520020,4.0,14.0,3.0,3.0,3.0,0.0,2453.41,5.109375,5.128906,3.199219
5894,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,6.0,14.0,3.0,3.0,2.0,0.0,2453.69,5.089844,5.128906,3.119141

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5895 entries, 0 to 5894
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Shape_CUSHION   5895 non-null   float64
 1   Shape_EMERALD   5895 non-null   float64
 2   Shape_HEART     5895 non-null   float64
 3   Shape_MARQUISE  5895 non-null   float64
 4   Shape_OVAL      5895 non-null   float64
 5   Shape_PEAR      5895 non-null   float64
 6   Shape_PRINCESS  5895 non-null   float64
 7   Shape_ROUND     5895 non-null   float64
 8   Weight          5895 non-null   float64
 9   Clarity         5895 non-null   float64
 10  Colour          5895 non-null   float64
 11  Cut             5895 non-null   float64
 12  Polish          5895 non-null   float64
 13  Symmetry        5895 non-null   float64
 14  Fluorescence    5895 non-null   float64
 15  Price           5895 non-null   float64
 16  Length          5895 non-null   float64
 17  Width           5895 non-null   float64
 18  Depth           5895 non-null   float64
dtypes: float64(19)
memory usage: 875.2 KB

In [5]:
# df.describe().T

In [6]:
# df.corr(numeric_only = True)

use this model

- Gradient Boosting Regressor
- Random Forest Regressor
- CatBoost Regressor
- Light Gradient Boosting Machine
- Extra Trees Regressor
- AdaBoost Regressor
- Extreme Gradient Boosting
- Lasso Least Angle Regression
- Ridge Regression
- Bayesian Ridge
- Least Angle Regression
- Lasso Regression
- Linear Regression
- Huber Regressor
- Decision Tree Regressor
- Orthogonal Matching Pursuit
- Passive Aggressive Regressor
- Elastic Net
- K Neighbors Regressor
- Dummy Regressor

Compare this models using MAE	MSE	RMSE	R2	RMSLE	MAPE	TT (Sec)
Also apply k-fold = 10

In [7]:
models = {'Gradient Boosting Regressor': GradientBoostingRegressor(),
          'Random Forest Regressor': RandomForestRegressor(),
          'CatBoost Regressor': CatBoostRegressor(verbose=0),
          'Light Gradient Boosting Machine': LGBMRegressor(),
          'Extra Trees Regressor': ExtraTreesRegressor(),
          'AdaBoost Regressor': AdaBoostRegressor(),
          'Extreme Gradient Boosting': XGBRegressor(),
          'Lasso Least Angle Regression': LassoLars(),
          'Ridge Regression': Ridge(),
          'Bayesian Ridge': BayesianRidge(),
          'Least Angle Regression': LassoLars(),
          'Lasso Regression': Lasso(),
          'Linear Regression': LinearRegression(),
          'Huber Regressor': HuberRegressor(max_iter=1000),
          'Decision Tree Regressor': DecisionTreeRegressor(),
          'Orthogonal Matching Pursuit': PassiveAggressiveRegressor(),
          'Passive Aggressive Regressor': PassiveAggressiveRegressor(),
          'Elastic Net': ElasticNet(),
          'K Neighbors Regressor': KNeighborsRegressor(),
          'Dummy Regressor': DummyRegressor()}

In [8]:
# Split the dataset into training and testing sets
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [9]:
# X_train = X_train.reset_index(drop=True)
# X_test = X_test.reset_index(drop=True)
# y_train = y_train.reset_index(drop=True)
# y_test = y_test.reset_index(drop=True)

In [10]:
# X_train

In [11]:
# Define the k-fold cross-validator
k_fold = KFold(n_splits=3, shuffle=True, random_state=42)

In [12]:
# stratified_fold = StratifiedKFold(n_splits=3, shuffle=True, random_state=42)

In [13]:
mae = []
mse = []
rmse= []
r2 = []
tt = []

test_mae = []
test_mse = []
test_rmse= []
test_r2 = []
test_tt = []

for model_name, model in models.items():
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    r2_scores = []
    tt_scores = []
    print(f"Model name: {model_name}\n")
    print("Train model")

    for k, (train_index, val_index) in enumerate(k_fold.split(X_train, y_train)):
        X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
        y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

        start_time = time.time()
        model.fit(X_train_fold, y_train_fold)
        y_pred = model.predict(X_val_fold)
        end_time = time.time()

        mae_scores.append(round(mean_absolute_error(y_val_fold, y_pred), 4))
        mse_scores.append(round(mean_squared_error(y_val_fold, y_pred), 4))
        rmse_scores.append(round(mean_squared_error(y_val_fold, y_pred, squared=False), 4))
        r2_scores.append(round(r2_score(y_val_fold, y_pred), 4))
        tt_scores.append(round(end_time - start_time, 4))
        
        print(f"Fold: {k}\tMAE: {mae_scores[-1]:.4f}\tMSE: {mse_scores[-1]:.4f}\tRMSE: {rmse_scores[-1]:.4f}\tR2: {r2_scores[-1]:.4f}\tTT: {tt_scores[-1]:.4f}")

    
    mae.append(np.mean(mae_scores))
    mse.append(np.mean(mse_scores))
    rmse.append(np.mean(rmse_scores))
    r2.append(np.mean(r2_scores))
    tt.append(np.mean(tt_scores))
    
    print("\nTest model")
    start_time = time.time()
    y_pred = model.predict(X_test)
    end_time = time.time()

    mae_scores.append(round(mean_absolute_error(y_test, y_pred), 4))
    mse_scores.append(round(mean_squared_error(y_test, y_pred), 4))
    rmse_scores.append(round(mean_squared_error(y_test, y_pred, squared=False), 4))
    r2_scores.append(round(r2_score(y_test, y_pred), 4))
    tt_scores.append(round(end_time - start_time, 4))
    
    print(f"Fold: -\tMAE: {mae_scores[-1]:.4f}\tMSE: {mse_scores[-1]:.4f}\tRMSE: {rmse_scores[-1]:.4f}\tR2: {r2_scores[-1]:.4f}\tTT: {tt_scores[-1]:.4f}")
    
    test_mae.append(mae_scores[-1])
    test_mse.append(mse_scores[-1])
    test_rmse.append(rmse_scores[-1])
    test_r2.append(r2_scores[-1])
    test_tt.append(tt_scores[-1])
    
    print("\n"+"="*100+"\n")

Model name: Gradient Boosting Regressor

Train model
Fold: 0	MAE: 224.4742	MSE: 261786.6889	RMSE: 511.6509	R2: 0.8873	TT: 1.3812
Fold: 1	MAE: 254.0686	MSE: 463045.3509	RMSE: 680.4744	R2: 0.8503	TT: 1.0550
Fold: 2	MAE: 230.4591	MSE: 350819.7556	RMSE: 592.3004	R2: 0.8686	TT: 1.0296

Test model
Fold: -	MAE: 246.8572	MSE: 426925.6156	RMSE: 653.3955	R2: 0.8470	TT: 0.0087

====================================================================================================

Model name: Random Forest Regressor

Train model
Fold: 0	MAE: 201.7793	MSE: 310273.3054	RMSE: 557.0218	R2: 0.8665	TT: 3.9241
Fold: 1	MAE: 221.4330	MSE: 467743.6018	RMSE: 683.9178	R2: 0.8488	TT: 4.1782
Fold: 2	MAE: 217.7371	MSE: 379933.0313	RMSE: 616.3871	R2: 0.8577	TT: 3.9793

Test model
Fold: -	MAE: 225.4351	MSE: 401770.8388	RMSE: 633.8540	R2: 0.8560	TT: 0.0853

====================================================================================================

Model name: CatBoost Regressor

Train model
Fold: 0	MAE: 182.1255	MSE: 215888.5609	RMSE: 464.6381	R2: 0.9071	TT: 8.7210
Fold: 1	MAE: 193.9445	MSE: 316682.7852	RMSE: 562.7458	R2: 0.8976	TT: 3.0992
Fold: 2	MAE: 191.5294	MSE: 297471.0645	RMSE: 545.4091	R2: 0.8886	TT: 3.2698

Test model
Fold: -	MAE: 202.1886	MSE: 355454.9561	RMSE: 596.2004	R2: 0.8726	TT: 0.0217

====================================================================================================

Model name: Light Gradient Boosting Machine

Train model
Fold: 0	MAE: 204.1293	MSE: 348110.1059	RMSE: 590.0086	R2: 0.8502	TT: 2.7479
Fold: 1	MAE: 221.4395	MSE: 439893.5187	RMSE: 663.2447	R2: 0.8578	TT: 1.7162
Fold: 2	MAE: 214.2691	MSE: 388797.4080	RMSE: 623.5362	R2: 0.8544	TT: 1.2186

Test model
Fold: -	MAE: 231.0250	MSE: 446256.2799	RMSE: 668.0242	R2: 0.8400	TT: 0.0208

====================================================================================================

Model name: Extra Trees Regressor

Train model
Fold: 0	MAE: 199.1166	MSE: 306511.6439	RMSE: 553.6349	R2: 0.8681	TT: 2.5723
Fold: 1	MAE: 217.3848	MSE: 483513.8175	RMSE: 695.3516	R2: 0.8437	TT: 2.6124
Fold: 2	MAE: 203.9520	MSE: 331312.0341	RMSE: 575.5971	R2: 0.8759	TT: 2.7334

Test model
Fold: -	MAE: 220.1562	MSE: 416269.3360	RMSE: 645.1894	R2: 0.8508	TT: 0.0910

====================================================================================================

Model name: AdaBoost Regressor

Train model
Fold: 0	MAE: 823.8117	MSE: 1110159.4880	RMSE: 1053.6411	R2: 0.5222	TT: 0.6483
Fold: 1	MAE: 613.6519	MSE: 913084.6034	RMSE: 955.5546	R2: 0.7048	TT: 0.5781
Fold: 2	MAE: 919.4746	MSE: 1327973.7569	RMSE: 1152.3774	R2: 0.5027	TT: 0.5697

Test model
Fold: -	MAE: 956.5585	MSE: 1414042.8573	RMSE: 1189.1353	R2: 0.4931	TT: 0.0254

====================================================================================================

Model name: Extreme Gradient Boosting

Train model
Fold: 0	MAE: 193.0051	MSE: 276306.7823	RMSE: 525.6489	R2: 0.8811	TT: 5.6792
Fold: 1	MAE: 226.3442	MSE: 507536.0630	RMSE: 712.4157	R2: 0.8359	TT: 5.9836
Fold: 2	MAE: 211.5367	MSE: 423092.3072	RMSE: 650.4555	R2: 0.8416	TT: 4.1827

Test model
Fold: -	MAE: 218.7702	MSE: 402100.4075	RMSE: 634.1139	R2: 0.8559	TT: 0.0179

====================================================================================================

Model name: Lasso Least Angle Regression

Train model
Fold: 0	MAE: 422.3800	MSE: 708668.1096	RMSE: 841.8243	R2: 0.6950	TT: 0.2744
Fold: 1	MAE: 416.9615	MSE: 826345.5484	RMSE: 909.0355	R2: 0.7328	TT: 0.0331
Fold: 2	MAE: 404.6732	MSE: 705413.2795	RMSE: 839.8888	R2: 0.7358	TT: 0.0219

Test model
Fold: -	MAE: 447.3380	MSE: 820998.1042	RMSE: 906.0895	R2: 0.7057	TT: 0.0049

====================================================================================================

Model name: Ridge Regression

Train model
Fold: 0	MAE: 423.4085	MSE: 706067.0310	RMSE: 840.2779	R2: 0.6961	TT: 0.0851
Fold: 1	MAE: 420.5534	MSE: 829266.5141	RMSE: 910.6407	R2: 0.7319	TT: 0.0077
Fold: 2	MAE: 404.9881	MSE: 702849.6572	RMSE: 838.3613	R2: 0.7368	TT: 0.0111

Test model
Fold: -	MAE: 447.5752	MSE: 817691.7782	RMSE: 904.2631	R2: 0.7069	TT: 0.0047

====================================================================================================

Model name: Bayesian Ridge

Train model
Fold: 0	MAE: 425.4249	MSE: 707898.7468	RMSE: 841.3672	R2: 0.6953	TT: 0.0654
Fold: 1	MAE: 421.8614	MSE: 825978.7875	RMSE: 908.8338	R2: 0.7330	TT: 0.0209
Fold: 2	MAE: 406.3053	MSE: 701626.7528	RMSE: 837.6316	R2: 0.7373	TT: 0.0200

Test model
Fold: -	MAE: 448.9835	MSE: 818388.7856	RMSE: 904.6484	R2: 0.7066	TT: 0.0043

====================================================================================================

Model name: Least Angle Regression

Train model
Fold: 0	MAE: 422.3800	MSE: 708668.1096	RMSE: 841.8243	R2: 0.6950	TT: 0.0188
Fold: 1	MAE: 416.9615	MSE: 826345.5484	RMSE: 909.0355	R2: 0.7328	TT: 0.0258
Fold: 2	MAE: 404.6732	MSE: 705413.2795	RMSE: 839.8888	R2: 0.7358	TT: 0.0202

Test model
Fold: -	MAE: 447.3380	MSE: 820998.1042	RMSE: 906.0895	R2: 0.7057	TT: 0.0030

====================================================================================================

Model name: Lasso Regression

Train model
Fold: 0	MAE: 422.3736	MSE: 708677.0781	RMSE: 841.8296	R2: 0.6950	TT: 0.0442
Fold: 1	MAE: 416.9519	MSE: 826360.9234	RMSE: 909.0440	R2: 0.7328	TT: 0.0197
Fold: 2	MAE: 404.6721	MSE: 705437.9951	RMSE: 839.9036	R2: 0.7358	TT: 0.0346

Test model
Fold: -	MAE: 447.3362	MSE: 821009.2721	RMSE: 906.0956	R2: 0.7057	TT: 0.0036

====================================================================================================

Model name: Linear Regression

Train model
Fold: 0	MAE: 426.6892	MSE: 709112.3539	RMSE: 842.0881	R2: 0.6948	TT: 0.1202
Fold: 1	MAE: 422.4118	MSE: 824691.6915	RMSE: 908.1254	R2: 0.7334	TT: 0.0264
Fold: 2	MAE: 406.8937	MSE: 701164.6136	RMSE: 837.3557	R2: 0.7374	TT: 0.0121

Test model
Fold: -	MAE: 449.6118	MSE: 819309.7665	RMSE: 905.1573	R2: 0.7063	TT: 0.0044

====================================================================================================

Model name: Huber Regressor

Train model
Fold: 0	MAE: 359.8739	MSE: 761929.0879	RMSE: 872.8855	R2: 0.6721	TT: 2.9168
Fold: 1	MAE: 374.8617	MSE: 1023029.2479	RMSE: 1011.4491	R2: 0.6692	TT: 1.3385
Fold: 2	MAE: 363.4559	MSE: 876132.6282	RMSE: 936.0196	R2: 0.6719	TT: 1.2757

Test model
Fold: -	MAE: 395.6969	MSE: 976864.2088	RMSE: 988.3644	R2: 0.6498	TT: 0.0045

====================================================================================================

Model name: Decision Tree Regressor

Train model
Fold: 0	MAE: 257.5725	MSE: 637696.4833	RMSE: 798.5590	R2: 0.7256	TT: 0.0662
Fold: 1	MAE: 298.6790	MSE: 800873.9517	RMSE: 894.9156	R2: 0.7411	TT: 0.0491
Fold: 2	MAE: 286.3910	MSE: 850384.3950	RMSE: 922.1629	R2: 0.6816	TT: 0.0479

Test model
Fold: -	MAE: 277.0419	MSE: 638341.8677	RMSE: 798.9630	R2: 0.7712	TT: 0.0067

====================================================================================================

Model name: Orthogonal Matching Pursuit

Train model
Fold: 0	MAE: 449.9441	MSE: 848986.5629	RMSE: 921.4047	R2: 0.6346	TT: 0.1031
Fold: 1	MAE: 415.6723	MSE: 1051470.7402	RMSE: 1025.4125	R2: 0.6600	TT: 0.0876
Fold: 2	MAE: 380.3383	MSE: 893787.3806	RMSE: 945.4033	R2: 0.6653	TT: 0.0769

Test model
Fold: -	MAE: 410.8456	MSE: 988519.1083	RMSE: 994.2430	R2: 0.6456	TT: 0.0107

====================================================================================================

Model name: Passive Aggressive Regressor

Train model
Fold: 0	MAE: 576.4301	MSE: 916434.9834	RMSE: 957.3061	R2: 0.6056	TT: 0.0637
Fold: 1	MAE: 412.5346	MSE: 1127231.7763	RMSE: 1061.7117	R2: 0.6356	TT: 0.0592
Fold: 2	MAE: 399.6485	MSE: 959010.6289	RMSE: 979.2909	R2: 0.6409	TT: 0.0416

Test model
Fold: -	MAE: 415.5512	MSE: 1043708.1655	RMSE: 1021.6204	R2: 0.6259	TT: 0.0056

====================================================================================================

Model name: Elastic Net

Train model
Fold: 0	MAE: 455.9306	MSE: 1027701.6005	RMSE: 1013.7562	R2: 0.5577	TT: 0.0108
Fold: 1	MAE: 495.5149	MSE: 1491444.8868	RMSE: 1221.2473	R2: 0.5178	TT: 0.0128
Fold: 2	MAE: 457.8134	MSE: 1194069.3104	RMSE: 1092.7348	R2: 0.5529	TT: 0.0118

Test model
Fold: -	MAE: 484.7145	MSE: 1284176.6477	RMSE: 1133.2152	R2: 0.5397	TT: 0.0042

====================================================================================================

Model name: K Neighbors Regressor

Train model
Fold: 0	MAE: 331.9459	MSE: 526883.9191	RMSE: 725.8677	R2: 0.7732	TT: 0.6634
Fold: 1	MAE: 359.4695	MSE: 694365.6966	RMSE: 833.2861	R2: 0.7755	TT: 0.5555
Fold: 2	MAE: 349.6151	MSE: 772101.9009	RMSE: 878.6933	R2: 0.7109	TT: 0.4732

Test model
Fold: -	MAE: 360.9694	MSE: 739841.2326	RMSE: 860.1402	R2: 0.7348	TT: 0.0196

====================================================================================================

Model name: Dummy Regressor

Train model
Fold: 0	MAE: 821.5554	MSE: 2328095.8206	RMSE: 1525.8099	R2: -0.0020	TT: 0.0005
Fold: 1	MAE: 877.4982	MSE: 3095972.0884	RMSE: 1759.5375	R2: -0.0010	TT: 0.0012
Fold: 2	MAE: 855.9609	MSE: 2670586.7656	RMSE: 1634.1930	R2: -0.0001	TT: 0.0006

Test model
Fold: -	MAE: 859.7680	MSE: 2790455.0826	RMSE: 1670.4655	R2: -0.0003	TT: 0.0001

====================================================================================================

In [14]:
results = pd.DataFrame({
    'Model': list(models.keys()),
    'MAE': mae,
    'MSE': mse,
    'RMSE': rmse,
    'R2': r2,
    'TT (Sec)': tt
})

results.sort_values("R2", axis=0, ascending=False).reset_index(drop=True)

,Model,MAE,MSE,RMSE,R2,TT (Sec)
0,CatBoost Regressor,189.199800,2.766808e+05,524.264333,0.897767,5.030000
1,Gradient Boosting Regressor,236.333967,3.585506e+05,594.808567,0.868733,1.155267
2,Extra Trees Regressor,206.817800,3.737792e+05,608.194533,0.862567,2.639367
3,Random Forest Regressor,213.649800,3.859833e+05,619.108900,0.857667,4.027200
4,Light Gradient Boosting Machine,213.279300,3.922670e+05,625.596500,0.854133,1.894233
5,Extreme Gradient Boosting,210.295333,4.023117e+05,629.506700,0.852867,5.281833
6,K Neighbors Regressor,347.010167,6.644505e+05,812.615700,0.753200,0.564033
7,Linear Regression,418.664900,7.449896e+05,862.523067,0.721867,0.052900
8,Bayesian Ridge,417.863867,7.451681e+05,862.610867,0.721867,0.035433
9,Ridge Regression,416.316667,7.460611e+05,863.093300,0.721600,0.034633
10,Lasso Regression,414.665867,7.468253e+05,863.592400,0.721200,0.032833
11,Least Angle Regression,414.671567,7.468090e+05,863.582867,0.721200,0.021600
12,Lasso Least Angle Regression,414.671567,7.468090e+05,863.582867,0.721200,0.109800
13,Decision Tree Regressor,280.880833,7.629849e+05,871.879167,0.716100,0.054400
14,Huber Regressor,366.063833,8.870303e+05,940.118067,0.671067,1.843667
15,Orthogonal Matching Pursuit,415.318233,9.314149e+05,964.073500,0.653300,0.089200
16,Passive Aggressive Regressor,462.871067,1.000892e+06,999.436233,0.627367,0.054833
17,AdaBoost Regressor,785.646067,1.117073e+06,1053.857700,0.576567,0.598700
18,Elastic Net,469.752967,1.237739e+06,1109.246100,0.542800,0.011800
19,Dummy Regressor,851.671500,2.698218e+06,1639.846800,-0.001033,0.000767

In [15]:
test_results = pd.DataFrame({
    'Model': list(models.keys()),
    'MAE': test_mae,
    'MSE': test_mse,
    'RMSE': test_rmse,
    'R2': test_r2,
    'TT (Sec)': test_tt
})

test_results.sort_values("R2", axis=0, ascending=False).reset_index(drop=True)

,Model,MAE,MSE,RMSE,R2,TT (Sec)
0,CatBoost Regressor,202.1886,3.554550e+05,596.2004,0.8726,0.0217
1,Random Forest Regressor,225.4351,4.017708e+05,633.8540,0.8560,0.0853
2,Extreme Gradient Boosting,218.7702,4.021004e+05,634.1139,0.8559,0.0179
3,Extra Trees Regressor,220.1562,4.162693e+05,645.1894,0.8508,0.0910
4,Gradient Boosting Regressor,246.8572,4.269256e+05,653.3955,0.8470,0.0087
5,Light Gradient Boosting Machine,231.0250,4.462563e+05,668.0242,0.8400,0.0208
6,Decision Tree Regressor,277.0419,6.383419e+05,798.9630,0.7712,0.0067
7,K Neighbors Regressor,360.9694,7.398412e+05,860.1402,0.7348,0.0196
8,Ridge Regression,447.5752,8.176918e+05,904.2631,0.7069,0.0047
9,Bayesian Ridge,448.9835,8.183888e+05,904.6484,0.7066,0.0043
10,Linear Regression,449.6118,8.193098e+05,905.1573,0.7063,0.0044
11,Least Angle Regression,447.3380,8.209981e+05,906.0895,0.7057,0.0030
12,Lasso Regression,447.3362,8.210093e+05,906.0956,0.7057,0.0036
13,Lasso Least Angle Regression,447.3380,8.209981e+05,906.0895,0.7057,0.0049
14,Huber Regressor,395.6969,9.768642e+05,988.3644,0.6498,0.0045
15,Orthogonal Matching Pursuit,410.8456,9.885191e+05,994.2430,0.6456,0.0107
16,Passive Aggressive Regressor,415.5512,1.043708e+06,1021.6204,0.6259,0.0056
17,Elastic Net,484.7145,1.284177e+06,1133.2152,0.5397,0.0042
18,AdaBoost Regressor,956.5585,1.414043e+06,1189.1353,0.4931,0.0254
19,Dummy Regressor,859.7680,2.790455e+06,1670.4655,-0.0003,0.0001

So we select CatBoost Regressor