In [1]:
import pandas as pd
import numpy as np
import time

In [2]:
from sklearn.model_selection import train_test_split, KFold
from sklearn.ensemble import GradientBoostingRegressor, RandomForestRegressor, ExtraTreesRegressor, AdaBoostRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.linear_model import LassoLars, Ridge, BayesianRidge, Lasso, LinearRegression, HuberRegressor, PassiveAggressiveRegressor, ElasticNet
from sklearn.neighbors import KNeighborsRegressor
from sklearn.dummy import DummyRegressor
from lightgbm import LGBMRegressor
from xgboost import XGBRegressor
from catboost import CatBoostRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

In [3]:
df = pd.read_csv("./../data/transform_diamonds.csv")
df

,Shape_CUSHION,Shape_EMERALD,Shape_HEART,Shape_MARQUISE,Shape_OVAL,Shape_PEAR,Shape_PRINCESS,Shape_ROUND,Weight,Clarity,Colour,Cut,Polish,Symmetry,Fluorescence,Price,Length,Width,Depth
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.549805,3.0,17.0,3.0,3.0,2.0,0.0,1378.65,5.050781,4.351562,2.939453
1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.500000,8.0,19.0,3.0,3.0,2.0,2.0,1379.74,4.601562,4.308594,2.919922
2,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.509766,5.0,14.0,3.0,3.0,2.0,0.0,1380.19,4.710938,4.351562,2.939453
3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.500000,5.0,14.0,3.0,3.0,2.0,0.0,1380.61,4.910156,4.261719,2.880859
4,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.529785,4.0,18.0,3.0,2.0,2.0,0.0,1383.13,4.699219,4.460938,3.009766
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5890,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,4.0,17.0,3.0,3.0,3.0,0.0,2453.10,5.000000,5.039062,3.179688
5891,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,4.0,17.0,3.0,3.0,3.0,0.0,2453.10,5.031250,5.058594,3.160156
5892,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,5.0,18.0,2.0,3.0,2.0,0.0,2453.20,4.929688,4.960938,3.189453
5893,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.520020,4.0,14.0,3.0,3.0,3.0,0.0,2453.41,5.109375,5.128906,3.199219
5894,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.500000,6.0,14.0,3.0,3.0,2.0,0.0,2453.69,5.089844,5.128906,3.119141

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5895 entries, 0 to 5894
Data columns (total 19 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Shape_CUSHION   5895 non-null   float64
 1   Shape_EMERALD   5895 non-null   float64
 2   Shape_HEART     5895 non-null   float64
 3   Shape_MARQUISE  5895 non-null   float64
 4   Shape_OVAL      5895 non-null   float64
 5   Shape_PEAR      5895 non-null   float64
 6   Shape_PRINCESS  5895 non-null   float64
 7   Shape_ROUND     5895 non-null   float64
 8   Weight          5895 non-null   float64
 9   Clarity         5895 non-null   float64
 10  Colour          5895 non-null   float64
 11  Cut             5895 non-null   float64
 12  Polish          5895 non-null   float64
 13  Symmetry        5895 non-null   float64
 14  Fluorescence    5895 non-null   float64
 15  Price           5895 non-null   float64
 16  Length          5895 non-null   float64
 17  Width           5895 non-null   float64
 18  Depth           5895 non-null   float64
dtypes: float64(19)
memory usage: 875.2 KB

use this model

- Gradient Boosting Regressor
- Random Forest Regressor
- CatBoost Regressor
- Light Gradient Boosting Machine
- Extra Trees Regressor
- AdaBoost Regressor
- Extreme Gradient Boosting
- Lasso Least Angle Regression
- Ridge Regression
- Bayesian Ridge
- Least Angle Regression
- Lasso Regression
- Linear Regression
- Huber Regressor
- Decision Tree Regressor
- Orthogonal Matching Pursuit
- Passive Aggressive Regressor
- Elastic Net
- K Neighbors Regressor
- Dummy Regressor

Compare this models using MAE	MSE	RMSE	R2	RMSLE	MAPE	TT (Sec)
Also apply k-fold = 10

In [5]:
# Split the dataset into training and testing sets
X = df.drop('Price', axis=1)
y = df['Price']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [6]:
models = {'Gradient Boosting Regressor': GradientBoostingRegressor(),
          'Random Forest Regressor': RandomForestRegressor(),
          'CatBoost Regressor': CatBoostRegressor(verbose=0),
          'Light Gradient Boosting Machine': LGBMRegressor(),
          'Extra Trees Regressor': ExtraTreesRegressor(),
          'AdaBoost Regressor': AdaBoostRegressor(),
          'Extreme Gradient Boosting': XGBRegressor(),
          'Lasso Least Angle Regression': LassoLars(),
          'Ridge Regression': Ridge(),
          'Bayesian Ridge': BayesianRidge(),
          'Least Angle Regression': LassoLars(),
          'Lasso Regression': Lasso(),
          'Linear Regression': LinearRegression(),
          'Huber Regressor': HuberRegressor(max_iter=1000),
          'Decision Tree Regressor': DecisionTreeRegressor(),
          'Orthogonal Matching Pursuit': PassiveAggressiveRegressor(),
          'Passive Aggressive Regressor': PassiveAggressiveRegressor(),
          'Elastic Net': ElasticNet(),
          'K Neighbors Regressor': KNeighborsRegressor(),
          'Dummy Regressor': DummyRegressor()}

In [7]:
# Define the k-fold cross-validator
k_fold = KFold(n_splits=3, shuffle=True, random_state=42)

In [8]:
mae = []
mse = []
rmse= []
r2 = []
tt = []

test_mae = []
test_mse = []
test_rmse= []
test_r2 = []
test_tt = []

for model_name, model in models.items():
    mae_scores = []
    mse_scores = []
    rmse_scores = []
    r2_scores = []
    tt_scores = []
    print(f"Model name: {model_name}\n")
    print("Train model")

    for k, (train_index, val_index) in enumerate(k_fold.split(X_train, y_train)):
        X_train_fold, X_val_fold = X_train.iloc[train_index], X_train.iloc[val_index]
        y_train_fold, y_val_fold = y_train.iloc[train_index], y_train.iloc[val_index]

        start_time = time.time()
        model.fit(X_train_fold, y_train_fold)
        y_pred = model.predict(X_val_fold)
        end_time = time.time()

        mae_scores.append(round(mean_absolute_error(y_val_fold, y_pred), 4))
        mse_scores.append(round(mean_squared_error(y_val_fold, y_pred), 4))
        rmse_scores.append(round(mean_squared_error(y_val_fold, y_pred, squared=False), 4))
        r2_scores.append(round(r2_score(y_val_fold, y_pred), 4))
        tt_scores.append(round(end_time - start_time, 4))
        
        print(f"Fold: {k}\tMAE: {mae_scores[-1]:.4f}\tMSE: {mse_scores[-1]:.4f}\tRMSE: {rmse_scores[-1]:.4f}\tR2: {r2_scores[-1]:.4f}\tTT: {tt_scores[-1]:.4f}")

    
    mae.append(np.mean(mae_scores))
    mse.append(np.mean(mse_scores))
    rmse.append(np.mean(rmse_scores))
    r2.append(np.mean(r2_scores))
    tt.append(np.mean(tt_scores))
    
    print("\nTest model")
    start_time = time.time()
    y_pred = model.predict(X_test)
    end_time = time.time()

    mae_scores.append(round(mean_absolute_error(y_test, y_pred), 4))
    mse_scores.append(round(mean_squared_error(y_test, y_pred), 4))
    rmse_scores.append(round(mean_squared_error(y_test, y_pred, squared=False), 4))
    r2_scores.append(round(r2_score(y_test, y_pred), 4))
    tt_scores.append(round(end_time - start_time, 4))
    
    print(f"Fold: -\tMAE: {mae_scores[-1]:.4f}\tMSE: {mse_scores[-1]:.4f}\tRMSE: {rmse_scores[-1]:.4f}\tR2: {r2_scores[-1]:.4f}\tTT: {tt_scores[-1]:.4f}")
    
    test_mae.append(mae_scores[-1])
    test_mse.append(mse_scores[-1])
    test_rmse.append(rmse_scores[-1])
    test_r2.append(r2_scores[-1])
    test_tt.append(tt_scores[-1])
    
    print("\n"+"="*100+"\n")

Model name: Gradient Boosting Regressor

Train model
Fold: 0	MAE: 224.7106	MSE: 263620.1339	RMSE: 513.4395	R2: 0.8865	TT: 0.4693
Fold: 1	MAE: 253.1302	MSE: 458105.3356	RMSE: 676.8348	R2: 0.8519	TT: 0.2910
Fold: 2	MAE: 230.3924	MSE: 350197.0419	RMSE: 591.7745	R2: 0.8689	TT: 0.2719

Test model
Fold: -	MAE: 247.6291	MSE: 430006.6018	RMSE: 655.7489	R2: 0.8459	TT: 0.0021

====================================================================================================

Model name: Random Forest Regressor

Train model
Fold: 0	MAE: 200.9388	MSE: 287328.3384	RMSE: 536.0302	R2: 0.8763	TT: 1.0292
Fold: 1	MAE: 226.0746	MSE: 491632.4137	RMSE: 701.1650	R2: 0.8411	TT: 0.9848
Fold: 2	MAE: 217.0834	MSE: 372590.1247	RMSE: 610.4016	R2: 0.8605	TT: 1.2634

Test model
Fold: -	MAE: 227.4485	MSE: 389658.9317	RMSE: 624.2267	R2: 0.8603	TT: 0.0361

====================================================================================================

Model name: CatBoost Regressor

Train model
Fold: 0	MAE: 182.1255	MSE: 215888.5609	RMSE: 464.6381	R2: 0.9071	TT: 39.4108
Fold: 1	MAE: 193.9445	MSE: 316682.7852	RMSE: 562.7458	R2: 0.8976	TT: 1.3369
Fold: 2	MAE: 191.5294	MSE: 297471.0645	RMSE: 545.4091	R2: 0.8886	TT: 1.2850

Test model
Fold: -	MAE: 202.1886	MSE: 355454.9561	RMSE: 596.2004	R2: 0.8726	TT: 0.0063

====================================================================================================

Model name: Light Gradient Boosting Machine

Train model
Fold: 0	MAE: 204.1293	MSE: 348110.1059	RMSE: 590.0086	R2: 0.8502	TT: 0.5349
Fold: 1	MAE: 221.4395	MSE: 439893.5187	RMSE: 663.2447	R2: 0.8578	TT: 0.1005
Fold: 2	MAE: 214.2691	MSE: 388797.4080	RMSE: 623.5362	R2: 0.8544	TT: 0.0985

Test model
Fold: -	MAE: 231.0250	MSE: 446256.2799	RMSE: 668.0242	R2: 0.8400	TT: 0.0033

====================================================================================================

Model name: Extra Trees Regressor

Train model
Fold: 0	MAE: 196.9634	MSE: 306127.7119	RMSE: 553.2881	R2: 0.8683	TT: 0.9240
Fold: 1	MAE: 215.4116	MSE: 451545.6284	RMSE: 671.9714	R2: 0.8540	TT: 0.7860
Fold: 2	MAE: 205.2374	MSE: 336272.3404	RMSE: 579.8899	R2: 0.8741	TT: 0.7644

Test model
Fold: -	MAE: 219.1753	MSE: 400444.9956	RMSE: 632.8072	R2: 0.8565	TT: 0.0327

====================================================================================================

Model name: AdaBoost Regressor

Train model
Fold: 0	MAE: 643.8317	MSE: 838876.7496	RMSE: 915.9022	R2: 0.6390	TT: 0.3268
Fold: 1	MAE: 615.8531	MSE: 927541.9515	RMSE: 963.0898	R2: 0.7001	TT: 0.1644
Fold: 2	MAE: 640.5912	MSE: 839553.3808	RMSE: 916.2715	R2: 0.6856	TT: 0.1808

Test model
Fold: -	MAE: 679.0819	MSE: 884088.9711	RMSE: 940.2601	R2: 0.6831	TT: 0.0083

====================================================================================================

Model name: Extreme Gradient Boosting

Train model
Fold: 0	MAE: 193.0051	MSE: 276306.7823	RMSE: 525.6489	R2: 0.8811	TT: 4.1706
Fold: 1	MAE: 226.3442	MSE: 507536.0630	RMSE: 712.4157	R2: 0.8359	TT: 0.8080
Fold: 2	MAE: 211.5367	MSE: 423092.3072	RMSE: 650.4555	R2: 0.8416	TT: 0.9336

Test model
Fold: -	MAE: 218.7702	MSE: 402100.4075	RMSE: 634.1139	R2: 0.8559	TT: 0.0275

====================================================================================================

Model name: Lasso Least Angle Regression

Train model
Fold: 0	MAE: 422.3800	MSE: 708668.1096	RMSE: 841.8243	R2: 0.6950	TT: 0.2483
Fold: 1	MAE: 416.9615	MSE: 826345.5484	RMSE: 909.0355	R2: 0.7328	TT: 0.0172
Fold: 2	MAE: 404.6732	MSE: 705413.2795	RMSE: 839.8888	R2: 0.7358	TT: 0.0109

Test model
Fold: -	MAE: 447.3380	MSE: 820998.1042	RMSE: 906.0895	R2: 0.7057	TT: 0.0027

====================================================================================================

Model name: Ridge Regression

Train model
Fold: 0	MAE: 423.4085	MSE: 706067.0310	RMSE: 840.2779	R2: 0.6961	TT: 0.0449
Fold: 1	MAE: 420.5534	MSE: 829266.5141	RMSE: 910.6407	R2: 0.7319	TT: 0.0051
Fold: 2	MAE: 404.9881	MSE: 702849.6572	RMSE: 838.3613	R2: 0.7368	TT: 0.0053

Test model
Fold: -	MAE: 447.5752	MSE: 817691.7782	RMSE: 904.2631	R2: 0.7069	TT: 0.0016

====================================================================================================

Model name: Bayesian Ridge

Train model
Fold: 0	MAE: 425.4249	MSE: 707898.7468	RMSE: 841.3672	R2: 0.6953	TT: 0.0426
Fold: 1	MAE: 421.8614	MSE: 825978.7875	RMSE: 908.8338	R2: 0.7330	TT: 0.0106
Fold: 2	MAE: 406.3053	MSE: 701626.7528	RMSE: 837.6316	R2: 0.7373	TT: 0.0106

Test model
Fold: -	MAE: 448.9835	MSE: 818388.7856	RMSE: 904.6484	R2: 0.7066	TT: 0.0017

====================================================================================================

Model name: Least Angle Regression

Train model
Fold: 0	MAE: 422.3800	MSE: 708668.1096	RMSE: 841.8243	R2: 0.6950	TT: 0.0128
Fold: 1	MAE: 416.9615	MSE: 826345.5484	RMSE: 909.0355	R2: 0.7328	TT: 0.0121
Fold: 2	MAE: 404.6732	MSE: 705413.2795	RMSE: 839.8888	R2: 0.7358	TT: 0.0100

Test model
Fold: -	MAE: 447.3380	MSE: 820998.1042	RMSE: 906.0895	R2: 0.7057	TT: 0.0017

====================================================================================================

Model name: Lasso Regression

Train model
Fold: 0	MAE: 422.3736	MSE: 708677.0781	RMSE: 841.8296	R2: 0.6950	TT: 0.0537
Fold: 1	MAE: 416.9519	MSE: 826360.9234	RMSE: 909.0440	R2: 0.7328	TT: 0.0107
Fold: 2	MAE: 404.6721	MSE: 705437.9951	RMSE: 839.9036	R2: 0.7358	TT: 0.0163

Test model
Fold: -	MAE: 447.3362	MSE: 821009.2721	RMSE: 906.0956	R2: 0.7057	TT: 0.0033

====================================================================================================

Model name: Linear Regression

Train model
Fold: 0	MAE: 426.6892	MSE: 709112.3539	RMSE: 842.0881	R2: 0.6948	TT: 0.0403
Fold: 1	MAE: 422.4118	MSE: 824691.6915	RMSE: 908.1254	R2: 0.7334	TT: 0.0062
Fold: 2	MAE: 406.8937	MSE: 701164.6136	RMSE: 837.3557	R2: 0.7374	TT: 0.0078

Test model
Fold: -	MAE: 449.6118	MSE: 819309.7665	RMSE: 905.1573	R2: 0.7063	TT: 0.0019

====================================================================================================

Model name: Huber Regressor

Train model
Fold: 0	MAE: 359.8739	MSE: 761929.0879	RMSE: 872.8855	R2: 0.6721	TT: 0.6808
Fold: 1	MAE: 374.8617	MSE: 1023029.2479	RMSE: 1011.4491	R2: 0.6692	TT: 0.5848
Fold: 2	MAE: 363.4559	MSE: 876132.6282	RMSE: 936.0196	R2: 0.6719	TT: 0.5621

Test model
Fold: -	MAE: 395.6969	MSE: 976864.2088	RMSE: 988.3644	R2: 0.6498	TT: 0.0026

====================================================================================================

Model name: Decision Tree Regressor

Train model
Fold: 0	MAE: 256.6070	MSE: 599312.0627	RMSE: 774.1525	R2: 0.7421	TT: 0.0296
Fold: 1	MAE: 296.7233	MSE: 791486.7322	RMSE: 889.6554	R2: 0.7441	TT: 0.0298
Fold: 2	MAE: 283.5279	MSE: 822287.0482	RMSE: 906.8004	R2: 0.6921	TT: 0.0310

Test model
Fold: -	MAE: 276.7824	MSE: 565585.6686	RMSE: 752.0543	R2: 0.7973	TT: 0.0018

====================================================================================================

Model name: Orthogonal Matching Pursuit

Train model
Fold: 0	MAE: 413.9480	MSE: 819578.1965	RMSE: 905.3056	R2: 0.6473	TT: 0.0514
Fold: 1	MAE: 410.3097	MSE: 1061246.2700	RMSE: 1030.1681	R2: 0.6569	TT: 0.0335
Fold: 2	MAE: 380.2578	MSE: 882163.8863	RMSE: 939.2358	R2: 0.6697	TT: 0.0328

Test model
Fold: -	MAE: 414.2705	MSE: 982812.3381	RMSE: 991.3689	R2: 0.6477	TT: 0.0012

====================================================================================================

Model name: Passive Aggressive Regressor

Train model
Fold: 0	MAE: 374.0188	MSE: 801460.2476	RMSE: 895.2431	R2: 0.6551	TT: 0.0309
Fold: 1	MAE: 383.2347	MSE: 1069272.3749	RMSE: 1034.0563	R2: 0.6543	TT: 0.0328
Fold: 2	MAE: 375.7383	MSE: 897281.6797	RMSE: 947.2495	R2: 0.6640	TT: 0.0384

Test model
Fold: -	MAE: 406.3485	MSE: 993738.0843	RMSE: 996.8641	R2: 0.6438	TT: 0.0017

====================================================================================================

Model name: Elastic Net

Train model
Fold: 0	MAE: 455.9306	MSE: 1027701.6005	RMSE: 1013.7562	R2: 0.5577	TT: 0.0063
Fold: 1	MAE: 495.5149	MSE: 1491444.8868	RMSE: 1221.2473	R2: 0.5178	TT: 0.0050
Fold: 2	MAE: 457.8134	MSE: 1194069.3104	RMSE: 1092.7348	R2: 0.5529	TT: 0.0072

Test model
Fold: -	MAE: 484.7145	MSE: 1284176.6477	RMSE: 1133.2152	R2: 0.5397	TT: 0.0017

====================================================================================================

Model name: K Neighbors Regressor

Train model
Fold: 0	MAE: 331.9459	MSE: 526883.9191	RMSE: 725.8677	R2: 0.7732	TT: 0.2323
Fold: 1	MAE: 359.4695	MSE: 694365.6966	RMSE: 833.2861	R2: 0.7755	TT: 0.0178
Fold: 2	MAE: 349.6151	MSE: 772101.9009	RMSE: 878.6933	R2: 0.7109	TT: 0.0218

Test model
Fold: -	MAE: 360.9694	MSE: 739841.2326	RMSE: 860.1402	R2: 0.7348	TT: 0.0147

====================================================================================================

Model name: Dummy Regressor

Train model
Fold: 0	MAE: 821.5554	MSE: 2328095.8206	RMSE: 1525.8099	R2: -0.0020	TT: 0.0003
Fold: 1	MAE: 877.4982	MSE: 3095972.0884	RMSE: 1759.5375	R2: -0.0010	TT: 0.0003
Fold: 2	MAE: 855.9609	MSE: 2670586.7656	RMSE: 1634.1930	R2: -0.0001	TT: 0.0003

Test model
Fold: -	MAE: 859.7680	MSE: 2790455.0826	RMSE: 1670.4655	R2: -0.0003	TT: 0.0000

====================================================================================================

In [9]:
results = pd.DataFrame({
    'Model': list(models.keys()),
    'MAE': mae,
    'MSE': mse,
    'RMSE': rmse,
    'R2': r2,
    'TT (Sec)': tt
})

results.sort_values("R2", axis=0, ascending=False).reset_index(drop=True)

,Model,MAE,MSE,RMSE,R2,TT (Sec)
0,CatBoost Regressor,189.199800,2.766808e+05,524.264333,0.897767,14.010900
1,Gradient Boosting Regressor,236.077733,3.573075e+05,594.016267,0.869100,0.344067
2,Extra Trees Regressor,205.870800,3.646486e+05,601.716467,0.865467,0.824800
3,Random Forest Regressor,214.698933,3.838503e+05,615.865600,0.859300,1.092467
4,Light Gradient Boosting Machine,213.279300,3.922670e+05,625.596500,0.854133,0.244633
5,Extreme Gradient Boosting,210.295333,4.023117e+05,629.506700,0.852867,1.970733
6,K Neighbors Regressor,347.010167,6.644505e+05,812.615700,0.753200,0.090633
7,Decision Tree Regressor,278.952733,7.376953e+05,856.869433,0.726100,0.030133
8,Linear Regression,418.664900,7.449896e+05,862.523067,0.721867,0.018100
9,Bayesian Ridge,417.863867,7.451681e+05,862.610867,0.721867,0.021267
10,Ridge Regression,416.316667,7.460611e+05,863.093300,0.721600,0.018433
11,Least Angle Regression,414.671567,7.468090e+05,863.582867,0.721200,0.011633
12,Lasso Regression,414.665867,7.468253e+05,863.592400,0.721200,0.026900
13,Lasso Least Angle Regression,414.671567,7.468090e+05,863.582867,0.721200,0.092133
14,AdaBoost Regressor,633.425333,8.686574e+05,931.754500,0.674900,0.224000
15,Huber Regressor,366.063833,8.870303e+05,940.118067,0.671067,0.609233
16,Orthogonal Matching Pursuit,401.505167,9.209961e+05,958.236500,0.657967,0.039233
17,Passive Aggressive Regressor,377.663933,9.226714e+05,958.849633,0.657800,0.034033
18,Elastic Net,469.752967,1.237739e+06,1109.246100,0.542800,0.006167
19,Dummy Regressor,851.671500,2.698218e+06,1639.846800,-0.001033,0.000300

In [10]:
test_results = pd.DataFrame({
    'Model': list(models.keys()),
    'MAE': test_mae,
    'MSE': test_mse,
    'RMSE': test_rmse,
    'R2': test_r2,
    'TT (Sec)': test_tt
})

test_results.sort_values("R2", axis=0, ascending=False).reset_index(drop=True)

,Model,MAE,MSE,RMSE,R2,TT (Sec)
0,CatBoost Regressor,202.1886,3.554550e+05,596.2004,0.8726,0.0063
1,Random Forest Regressor,227.4485,3.896589e+05,624.2267,0.8603,0.0361
2,Extra Trees Regressor,219.1753,4.004450e+05,632.8072,0.8565,0.0327
3,Extreme Gradient Boosting,218.7702,4.021004e+05,634.1139,0.8559,0.0275
4,Gradient Boosting Regressor,247.6291,4.300066e+05,655.7489,0.8459,0.0021
5,Light Gradient Boosting Machine,231.0250,4.462563e+05,668.0242,0.8400,0.0033
6,Decision Tree Regressor,276.7824,5.655857e+05,752.0543,0.7973,0.0018
7,K Neighbors Regressor,360.9694,7.398412e+05,860.1402,0.7348,0.0147
8,Ridge Regression,447.5752,8.176918e+05,904.2631,0.7069,0.0016
9,Bayesian Ridge,448.9835,8.183888e+05,904.6484,0.7066,0.0017
10,Linear Regression,449.6118,8.193098e+05,905.1573,0.7063,0.0019
11,Least Angle Regression,447.3380,8.209981e+05,906.0895,0.7057,0.0017
12,Lasso Regression,447.3362,8.210093e+05,906.0956,0.7057,0.0033
13,Lasso Least Angle Regression,447.3380,8.209981e+05,906.0895,0.7057,0.0027
14,AdaBoost Regressor,679.0819,8.840890e+05,940.2601,0.6831,0.0083
15,Huber Regressor,395.6969,9.768642e+05,988.3644,0.6498,0.0026
16,Orthogonal Matching Pursuit,414.2705,9.828123e+05,991.3689,0.6477,0.0012
17,Passive Aggressive Regressor,406.3485,9.937381e+05,996.8641,0.6438,0.0017
18,Elastic Net,484.7145,1.284177e+06,1133.2152,0.5397,0.0017
19,Dummy Regressor,859.7680,2.790455e+06,1670.4655,-0.0003,0.0000

So we select CatBoost Regressor